#!/usr/bin/env bash

# Run prettier on all staged files

# Get all staged files
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|jsx|ts|tsx)$')

# Exit if no files are staged
if [ -z "$staged_files" ]; then
  exit 0
fi

# Run prettier on all staged files
echo "$staged_files" | xargs ./node_modules/.bin/prettier --write

# Add all staged files
echo "$staged_files" | xargs git add

# Exit with success
exit 0
